import assert from 'node:assert/strict';
import {initialState,generateMenu,validateDay,type Dish} from '../lib/menu';
import {acceptRecipe,editPerson,poolFor,pilot,resolveRecipe,addSuggestions,suggestForDay} from '../lib/recipes';
import {fromProvider,refreshRecipes,sourceList} from '../lib/recipe-provider';
import {shoppingList} from '../lib/shopping';
const catalog:Dish[]=Array.from({length:5},(_,i)=>({id:i+1,name:`Plato ${i+1}`,category:'Verduras',season:'Ambos',complexity:2,diners:i===4?['Marta']:['Dani','Marta'],mealType:'Comida',type:'Único',review:false,recipe:{servings:1,ingredients:[{name:'Arroz',quantity:100,unit:'g'}],steps:[],sourceUrl:'',notes:'',reviewed:true}}));
const state=initialState();const month='2026-10';state.menus[month]=generateMenu(month,catalog,state.settings,state.menus);const menu=state.menus[month],date=menu.days[0].date;
const currentDay=()=>menu.days[0];
const marta=structuredClone(menu.days[0].meals.Marta);
editPerson(menu,catalog,state.menus,{date,person:'Dani',mode:'out',note:'Trabajo'},pilot);
assert.deepEqual(menu.days[0].meals.Marta,marta);assert.equal(menu.days[0].personal?.Dani.kind,'out');assert.deepEqual(menu.days[0].meals.Dani,[]);
validateDay(menu.days[0],menu.settings);
menu.status='confirmed';const shopping=shoppingList({...menu,days:[menu.days[0]]},catalog);assert.equal(shopping.portions,1);assert.equal(shopping.items[0].quantity,100);menu.status='draft';
editPerson(menu,catalog,state.menus,{date,person:'Dani',mode:'generate'},pilot);assert.equal(currentDay().personal?.Dani,undefined);assert.deepEqual(currentDay().meals.Marta,marta);assert.ok(currentDay().meals.Dani.every(d=>d.diners.includes('Dani')));
editPerson(menu,catalog,state.menus,{date,person:'Dani',mode:'suggest'},pilot);const proposal=currentDay().personal!.Dani;assert.equal(proposal.kind,'suggestion');if(proposal.kind!=='suggestion')throw Error();
const recipe={...proposal.recipe,type:'Único',season:'Ambos'};
state.discovery={recipes:[],updatedAt:new Date().toISOString()};assert.equal(resolveRecipe(state,recipe.id)?.id,recipe.id);
const dish={name:recipe.name,category:recipe.category,type:'Único',season:'Ambos',complexity:2,diners:['Dani'],mealType:'Comida' as const,review:false,enabled:true};
acceptRecipe(state,catalog,{recipeId:recipe.id,dish,month,date,targetPerson:'Dani'},recipe);assert.deepEqual(currentDay().meals.Marta,marta);assert.equal(state.added?.length,1);assert.equal(currentDay().meals.Dani[0].recipeId,recipe.id);assert.ok(state.added![0].recipe?.ingredients.length);assert.equal(currentDay().personal?.Dani,undefined);
assert.throws(()=>acceptRecipe(state,[...catalog,...state.added!],{recipeId:recipe.id,dish},recipe),/ya está/);
const other=pilot.find(r=>r.id!==recipe.id)!;const body={recipeId:other.id,dish:{...dish,name:other.name,diners:['Dani','Marta']},month,date,schedule:true};
const before=JSON.stringify(state);assert.throws(()=>acceptRecipe(state,[...catalog,...state.added!],body,other),/bloqueado/);assert.equal(JSON.stringify(state),before);
acceptRecipe(state,[...catalog,...state.added!],{...body,replaceLocked:true},{...other,type:'Único',season:'Ambos'});assert.equal(menu.days[0].meals.Marta[0].recipeId,other.id);
const next='2026-11';const newRecipe={...pilot[2],id:'abuela-999999',name:'Prueba nueva',type:'Único',season:'Ambos'};acceptRecipe(state,[...catalog,...state.added!],{recipeId:newRecipe.id,dish:{...dish,name:newRecipe.name},month:next,date:'2026-11-02',schedule:true},newRecipe);assert.equal(state.menus[next].status,'draft');assert.equal(state.menus[next].days[0].meals.Dani[0].recipeId,newRecipe.id);assert.ok(state.menus[next].days[0].meals.Marta.length);
const pendingState=initialState();const pending=addSuggestions(generateMenu(month,catalog,pendingState.settings,{}),catalog,{},undefined,pilot);pendingState.menus[month]=pending;const pendingDay=pending.days.find(d=>d.suggestion)!;const snap=pendingDay.suggestedRecipe!;acceptRecipe(pendingState,catalog,{recipeId:snap.id,dish:{...dish,name:snap.name},month,date:pendingDay.date,targetPerson:'Dani'},{...snap,type:'Único',season:'Ambos'});assert.equal(pendingDay.suggestion,snap.id);const changed=()=>pending.days.find(d=>d.date===pendingDay.date)!;assert.equal(changed().personal!.Marta.kind,'suggestion');assert.equal(changed().meals.Dani[0].recipeId,snap.id);
const row={row_idx:15,row:{Id:21,Nombre:'Pollo al horno',URL:'https://example.com/recipe',Ingredientes:'2,5 kg de pollo, Sal al gusto',Pasos:'Cocinar hasta que esté listo.',Comensales:'4 personas',Categoria:'Carnes'}};
const imported=fromProvider(row)!;assert.equal(imported.id,'abuela-21');assert.equal(imported.servings,4);assert.match(imported.ingredients[0],/2,5/);assert.equal(fromProvider({...row,row:{...row.row,URL:'javascript:alert(1)'}}),null);assert.equal(fromProvider({...row,truncated_cells:[1]}),null);
assert.deepEqual(sourceList("['1 pollo, troceado', 'Sal al gusto']"),['1 pollo, troceado','Sal al gusto']);
assert.equal(fromProvider({...row,row:{...row.row,Nombre:'cake pops de halloween'}}),null);
assert.equal(fromProvider({...row,row:{...row.row,Nombre:'crema de pistacho para relleno de postres'}}),null);
const originalFetch=globalThis.fetch;
globalThis.fetch=async()=>new Response('unavailable',{status:503});await assert.rejects(()=>refreshRecipes(pilot,catalog),/Conservamos/);globalThis.fetch=originalFetch;
console.log('PASS: individual edits, compatibility, shopping portions, proposal snapshots, acceptance, duplicates, locks, new month, source validation, provider failure.');
