'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Download,Upload} from 'lucide-react';
import {recipeFor} from '../lib/shopping';
import type {Dish} from '../lib/menu';
export function downloadText(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export function exportCatalog(catalog:Dish[]){downloadText('a-la-mesa-catalogo.json',JSON.stringify({format:'a-la-mesa.catalog',version:1,exportedAt:new Date().toISOString(),instructions:'Conserva el id para actualizar un plato; elimina el id para crear uno nuevo. Los platos ausentes se conservan. Para excluir uno, usa enabled:false. recipe.servings son las raciones de la receta; quantity:null significa cantidad desconocida. Revisa antes de poner recipe.reviewed:true. No cambies format ni version.',dishes:catalog.map(d=>({...d,recipe:recipeFor(d)}))},null,2))}
export default function ImportCatalog({revision,busy,onClose,onApply}:{revision:number;busy:boolean;onClose:()=>void;onApply:(document:unknown)=>Promise<void>}){
 const dialog=useRef<HTMLDialogElement>(null),file=useRef<HTMLInputElement>(null);const [document,setDocument]=useState<unknown>(null),[name,setName]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false),[preview,setPreview]=useState<{new:number;updated:number;unchanged:number;revision:number}|null>(null);
 useEffect(()=>{dialog.current?.showModal()},[]);
 async function review(){if(!document)return;setWorking(true);setError('');setPreview(null);try{const res=await fetch('/api/menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preview-import',document,revision})});const data=await res.json() as {error?:string;preview:{new:number;updated:number;unchanged:number};revision:number};if(!res.ok)throw Error(data.error);setPreview({...data.preview,revision:data.revision})}catch(e){setError(e instanceof Error?e.message:'No se pudo revisar el archivo.')}finally{setWorking(false)}}
 return <dialog ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose()}}><div className="dialog-header"><h2>Importar catálogo</h2><button aria-label="Cerrar importación" onClick={onClose}><X size={20}/></button></div><p>Exporta primero el catálogo, edita el JSON y vuelve a importarlo. Conserva los identificadores para actualizar platos; omítelos en los platos nuevos.</p><p className="footnote">Se conservan los platos que no aparezcan en el archivo y los menús guardados. La compra usa las recetas actuales, por lo que reflejará los cambios de ingredientes.</p><input ref={file} type="file" accept=".json,application/json" aria-label="Archivo de catálogo JSON" disabled={busy||working} onChange={async e=>{setError('');setPreview(null);setDocument(null);const f=e.target.files?.[0];if(!f)return;setName(f.name);try{if(f.size>1400000)throw Error('El archivo supera 1,4 MB. Divide los platos en varios archivos.');setDocument(JSON.parse((await f.text()).replace(/^\uFEFF/,'')))}catch(err){setError(err instanceof SyntaxError?'El archivo no contiene JSON válido. Comprueba comas y comillas.':err instanceof Error?err.message:'No se pudo leer el archivo.')}}}/>{name&&<p>{name}</p>}{preview&&<div className="recipe-note"><strong>Vista previa</strong><p>{preview.new} nuevos · {preview.updated} actualizados · {preview.unchanged} sin cambios.</p>{preview.revision!==revision&&<p>El catálogo ha cambiado. Revisa el archivo de nuevo.</p>}</div>}{error&&<p role="alert" className="dialog-error" style={{whiteSpace:'pre-wrap'}}>{error}</p>}<div className="dialog-actions"><button onClick={onClose}>Cancelar</button><button disabled={!document||busy||working} onClick={()=>void review()}>{working?'Revisando…':'Revisar archivo'}</button><button className="primary" disabled={!preview||preview.revision!==revision||busy||working} onClick={async()=>{try{await onApply(document);onClose()}catch(e){setError(e instanceof Error?e.message:'No se pudo importar.')}}}><Upload size={17}/>Aplicar cambios</button></div></dialog>;
}
