'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,X,RefreshCw,Sparkles} from 'lucide-react';
import {manualEntries,mealsFor,type Diner,type Day,type ManualMeal} from '../lib/menu';
import {pendingRecipe,type Recipe} from '../lib/recipes';
type Edit={mode:'out'|'tupper'|'custom'|'generate'|'suggest';person:string;note?:string};
export default function DayEditor({day,diners,busy,error,onClose,onSave,onPerson,onRecipe}:{day:Day;diners:Diner[];busy:boolean;error:string;onClose:()=>void;onSave:(value:ManualMeal)=>Promise<void>;onPerson:(edit:Edit)=>Promise<string|undefined>;onRecipe:(recipe:Recipe,person:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [empty,setEmpty]=useState(day.manual?.kind==='empty'),[note,setNote]=useState(day.manual&&day.manual.kind!=='custom'?day.manual.note:'');
 const [modes,setModes]=useState<Record<string,'out'|'tupper'|'custom'>>(()=>Object.fromEntries(diners.map(p=>{const personal=day.personal?.[p.id];return [p.id,personal&&personal.kind!=='suggestion'&&personal.kind!=='empty'?personal.kind:day.manual?.kind==='out'?'out':'tupper']})));
 const [notes,setNotes]=useState<Record<string,string>>(()=>Object.fromEntries(diners.map(p=>{const personal=day.personal?.[p.id];return [p.id,personal&&personal.kind!=='suggestion'?personal.note:day.manual?.kind==='custom'?manualEntries(day.manual)[p.id]??'':'']}))),[generated,setGenerated]=useState<Record<string,string>>({}),[message,setMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal()},[]);
 async function change(edit:Edit){setMessage('');try{const meal=await onPerson(edit);if(edit.mode==='generate'&&meal){setGenerated(old=>({...old,[edit.person]:meal}));setNotes(old=>({...old,[edit.person]:meal}))}setMessage('Comida de '+diners.find(p=>p.id===edit.person)?.name+' guardada. Las demás se han conservado.')}catch{}}
 return <dialog className="day-editor" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===dialog.current&&!busy)onClose()}}><div className="dialog-header"><div><p className="eyebrow">{new Date(day.date+'T12:00:00Z').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</p><h2>Editar comida del día</h2></div><button aria-label="Cerrar edición del día" disabled={busy} onClick={onClose}><X size={20}/></button></div>
 <label>¿Qué hacemos este día?<select value={empty?'empty':'people'} disabled={busy} onChange={e=>setEmpty(e.target.value==='empty')}><option value="people">Editar por comensal</option><option value="empty">Dejar sin planificar</option></select></label>
 {empty?<form onSubmit={async e=>{e.preventDefault();try{await onSave({kind:'empty',note:note.trim()})}catch{}}}><label>Nota opcional<textarea maxLength={240} rows={2} placeholder="Puedes dejarlo vacío" value={note} onChange={e=>setNote(e.target.value)}/></label><p className="footnote">No se asignarán platos a este día.</p><button className="primary" disabled={busy}><Check size={17}/>Guardar día</button></form>:<>{diners.map(p=>{const personal=day.personal?.[p.id],suggestion=personal?.kind==='suggestion'?personal.recipe:pendingRecipe(day);return <section className="person-editor" key={p.id}><h3>{p.name}</h3><p className="current-meal">{suggestion?'Por probar: '+suggestion.name:personal?personal.kind==='out'?'Fuera'+(personal.note?' · '+personal.note:''):personal.kind==='tupper'?'Tupper'+(personal.note?' · '+personal.note:''):personal.kind==='custom'?personal.note:'Sin planificar':day.manual?.kind==='custom'?manualEntries(day.manual)[p.id]:day.manual?.kind==='out'?'Fuera':(mealsFor(day,'Comida')[p.id]??[]).map(d=>d.name).join(' + ')||'Sin planificar'}</p>
 {suggestion&&<button disabled={busy} onClick={()=>onRecipe(suggestion,p.id)}>Ver y aceptar para {p.name}</button>}
 <form onSubmit={e=>{e.preventDefault();void change({person:p.id,mode:modes[p.id],note:notes[p.id]})}}><label>Opción para {p.name}<select disabled={busy} value={modes[p.id]} onChange={e=>{setModes({...modes,[p.id]:e.target.value as 'out'|'tupper'|'custom'});setGenerated(old=>{const next={...old};delete next[p.id];return next})}}><option value="tupper">Tupper</option><option value="out">Fuera</option><option value="custom">Comida puntual</option></select></label><label>{generated[p.id]||modes[p.id]==='custom'?'Qué va a comer':'Nota opcional'}<input required={modes[p.id]==='custom'} readOnly={!!generated[p.id]} disabled={busy} maxLength={240} value={notes[p.id]??''} onChange={e=>setNotes({...notes,[p.id]:e.target.value})}/></label><div className="person-actions"><button disabled={busy}>Guardar {modes[p.id]==='out'?'fuera':modes[p.id]==='tupper'?'tupper':'comida'}</button><button type="button" disabled={busy} onClick={()=>void change({person:p.id,mode:'generate'})}><RefreshCw size={16}/>Generar plato de comida</button><button type="button" disabled={busy} onClick={()=>void change({person:p.id,mode:'suggest'})}><Sparkles size={16}/>Pedir receta de comida</button></div></form></section>})}<p className="footnote">Generar plato y pedir receta modifican únicamente la comida de esa persona. La nota sigue siendo opcional para tupper y fuera. Cada cambio se guarda por separado y bloquea el día al regenerar el mes.</p></>}
 {message&&<p className="message success" role="status">{message}</p>}{error&&<p className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button disabled={busy} onClick={onClose}>Cerrar</button></div></dialog>;
}
