'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,X,RefreshCw,Sparkles} from 'lucide-react';
import {manualEntries,mealsFor,personalFor,type Diner,type Day,type ManualMeal,type MealType} from '../lib/menu';
import {pendingRecipe,type Recipe} from '../lib/recipes';
type Mode='out'|'tupper'|'custom';
type Edit={mode:Mode|'generate'|'suggest';person:string;mealType:MealType;note?:string};
const key=(type:MealType,person:string)=>`${type}:${person}`;
export default function DayEditor({day,diners,mealTypes,busy,error,onClose,onSave,onPerson,onRecipe}:{day:Day;diners:Diner[];mealTypes:MealType[];busy:boolean;error:string;onClose:()=>void;onSave:(value:ManualMeal)=>Promise<void>;onPerson:(edit:Edit)=>Promise<string|undefined>;onRecipe:(recipe:Recipe,person:string,mealType:MealType)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [empty,setEmpty]=useState(day.manual?.kind==='empty'),[note,setNote]=useState(day.manual&&day.manual.kind!=='custom'?day.manual.note:'');
 const [modes,setModes]=useState<Record<string,Mode>>(()=>Object.fromEntries(mealTypes.flatMap(type=>diners.map(p=>{const personal=personalFor(day,type)[p.id];return [key(type,p.id),personal&&personal.kind!=='suggestion'&&personal.kind!=='empty'?personal.kind:day.manual?.kind==='out'?'out':'custom']}))));
 const [notes,setNotes]=useState<Record<string,string>>(()=>Object.fromEntries(mealTypes.flatMap(type=>diners.map(p=>{const personal=personalFor(day,type)[p.id],current=(mealsFor(day,type)[p.id]??[]).map(d=>d.name).join(' + ');return [key(type,p.id),personal?.kind==='suggestion'?personal.recipe.name:personal?personal.note:day.manual?.kind==='custom'?manualEntries(day.manual)[p.id]??'':current]})))),[generated,setGenerated]=useState<Record<string,string>>({}),[message,setMessage]=useState('');
 useEffect(()=>{dialog.current?.showModal()},[]);
 async function change(edit:Edit){setMessage('');try{const meal=await onPerson(edit),k=key(edit.mealType,edit.person);if(edit.mode==='generate'&&meal){setGenerated(old=>({...old,[k]:meal}));setNotes(old=>({...old,[k]:meal}))}setMessage(`${edit.mealType} de ${diners.find(p=>p.id===edit.person)?.name} guardada. Las demás se han conservado.`)}catch{}}
 function description(type:MealType,person:string){const personal=personalFor(day,type)[person],shared=type==='Comida'?pendingRecipe(day):undefined,suggestion=personal?.kind==='suggestion'?personal.recipe:shared;if(suggestion)return 'Por probar: '+suggestion.name;if(personal)return personal.kind==='out'?'Fuera'+(personal.note?' · '+personal.note:''):personal.kind==='tupper'?'Tupper'+(personal.note?' · '+personal.note:''):personal.kind==='custom'?personal.note:'Sin planificar';return (mealsFor(day,type)[person]??[]).map(d=>d.name).join(' + ')||'Sin planificar'}
 return <dialog className="day-editor" ref={dialog} onCancel={onClose} onClick={e=>{if(e.target===dialog.current&&!busy)onClose()}}><div className="dialog-header"><div><p className="eyebrow">{new Date(day.date+'T12:00:00Z').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</p><h2>Editar menú del día</h2></div><button aria-label="Cerrar edición del día" disabled={busy} onClick={onClose}><X size={20}/></button></div>
 <label>¿Qué hacemos este día?<select value={empty?'empty':'people'} disabled={busy} onChange={e=>setEmpty(e.target.value==='empty')}><option value="people">Editar por comensal</option><option value="empty">Dejar sin planificar</option></select></label>
 {empty?<form onSubmit={async e=>{e.preventDefault();try{await onSave({kind:'empty',note:note.trim()})}catch{}}}><label>Nota opcional<textarea maxLength={240} rows={2} placeholder="Puedes dejarlo vacío" value={note} onChange={e=>setNote(e.target.value)}/></label><p className="footnote">No se asignarán platos a este día.</p><button className="primary" disabled={busy}><Check size={17}/>Guardar día</button></form>:<div className="meal-type-editors">{mealTypes.map(type=><section className="meal-type-editor" key={type}><h3>{type}</h3>{diners.map(p=>{const k=key(type,p.id),mode=modes[k],personal=personalFor(day,type)[p.id],shared=type==='Comida'?pendingRecipe(day):undefined,suggestion=personal?.kind==='suggestion'?personal.recipe:shared;return <section className="person-editor" key={p.id}><h4>{p.name}</h4><p className="current-meal">{description(type,p.id)}</p>
 {suggestion&&<button disabled={busy} onClick={()=>onRecipe(suggestion,p.id,type)}>Ver y aceptar para {p.name}</button>}
 <form onSubmit={e=>{e.preventDefault();void change({person:p.id,mealType:type,mode,note:notes[k]})}}><label>Opción para {p.name}<select disabled={busy} value={mode} onChange={e=>{setModes({...modes,[k]:e.target.value as Mode});setGenerated(old=>{const next={...old};delete next[k];return next})}}><option value="tupper">Tupper</option><option value="out">Fuera</option><option value="custom">Comida puntual</option></select></label><label>{generated[k]||mode==='custom'?'Qué va a comer':'Nota opcional'}<input required={mode==='custom'} readOnly={!!generated[k]} disabled={busy} maxLength={240} value={notes[k]??''} onChange={e=>setNotes({...notes,[k]:e.target.value})}/></label><div className="person-actions"><button disabled={busy}>Guardar {mode==='out'?'fuera':mode==='tupper'?'tupper':'comida puntual'}</button>{mode==='custom'&&<><button type="button" disabled={busy} onClick={()=>void change({person:p.id,mealType:type,mode:'generate'})}><RefreshCw size={16}/>Generar plato</button><button type="button" disabled={busy} onClick={()=>void change({person:p.id,mealType:type,mode:'suggest'})}><Sparkles size={16}/>Pedir receta</button></>}</div></form></section>})}</section>)}</div>}
 {!empty&&<p className="footnote">Cada tipo seleccionado en Preferencias se edita por separado. Generar plato y pedir receta solo están disponibles en Comida puntual. La nota sigue siendo opcional para tupper y fuera.</p>}
 {message&&<p className="message success" role="status">{message}</p>}{error&&<p className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button disabled={busy} onClick={onClose}>Cerrar</button></div></dialog>;
}