'use client';
import {useState,useEffect,useRef} from 'react';
import {CalendarDays,BookOpen,Settings2,Utensils,Sparkles,ChevronLeft,ChevronRight,RefreshCw,LockKeyhole,Unlock,Check,Search,X,Download,Pencil,History,AlertCircle,LoaderCircle,Plus,Upload,ShoppingBasket} from 'lucide-react';
import recipes from '../lib/recipes.json';
import {DiscoverRecipes,RecipeDialog,type Recipe} from './recipes';
import DishRecipe from './dish-recipe';
import Shopping from './shopping';
import ImportCatalog,{exportCatalog} from './catalog-transfer';
import DayEditor from './day-editor';
import seed from '../lib/catalog.json';
import {initialState,monthDates,normalize,people,type State,type Dish,type Settings,type Day} from '../lib/menu';
type Payload={state:State;revision:number;catalog:Dish[]};
const dayNames=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const categories=['Carne','Verduras','Pollo','Pescado','Pasta','Legumbres','Arroz','Huevos'];
function nextMonth(m:string,delta=1){const [y,n]=m.split('-').map(Number);const d=new Date(Date.UTC(y,n-1+delta,1));return d.toISOString().slice(0,7)}
function title(m:string){return `${months[Number(m.slice(5))-1]} ${m.slice(0,4)}`}
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function tag(category:string){return `category cat-${normalize(category)}`}
export default function Planner(){
 const [tab,setTab]=useState('menu');const [month,setMonth]=useState(()=>nextMonth(currentMonth()));
 const [data,setData]=useState<Payload>({state:initialState(),revision:0,catalog:seed as Dish[]});const latest=useRef(data);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[auth,setAuth]=useState(false);
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[person,setPerson]=useState(''),[onlyReview,setOnlyReview]=useState(false),[limit,setLimit]=useState(40);
 const [edit,setEdit]=useState<Dish|null>(null),[prefs,setPrefs]=useState<Settings>(initialState().settings);
 const [dishRecipe,setDishRecipe]=useState<Dish|null>(null),[importOpen,setImportOpen]=useState(false);
 const [recipeView,setRecipeView]=useState<{recipe:Recipe;date?:string}|null>(null);
 const [editDay,setEditDay]=useState<Day|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);const inflight=useRef(false);
 function accept(result:Payload){latest.current=result;setData(result)}
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/menu');const j=await r.json() as Payload & {error:string};if(!r.ok){setAuth(r.status===401);throw new Error(j.error)}accept(j);setPrefs(j.state.settings);setAuth(false)}catch(e){setError(e instanceof Error?e.message:'No se ha podido conectar.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function act(action:Record<string,unknown>,message='Cambios guardados'){
  if(inflight.current)throw new Error('Espera a que termine la operación actual.');inflight.current=true;setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/menu',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,revision:latest.current.revision})});const j=await r.json() as Payload & {error:string};if(!r.ok)throw new Error(j.error);accept(j);setNotice(message);return j as Payload}catch(e){setError(e instanceof Error?e.message:'No se han guardado los cambios.');throw e}finally{inflight.current=false;setBusy(false)}
 }
 function run(action:Record<string,unknown>,message?:string){void act(action,message).catch(()=>{})}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();
  Promise.resolve(ctx.registerTool({name:'read_meal_plans',description:'Consulta los menús y las preferencias guardadas de Dani y Marta.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({months:Object.values(latest.current.state.menus),settings:latest.current.state.settings})},{signal:lifecycle.signal})).catch(()=>{});
  Promise.resolve(ctx.registerTool({name:'generate_month_draft',description:'Genera y guarda el borrador de un mes. Conserva los días bloqueados y no modifica meses confirmados.',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^20[0-9]{2}-(0[1-9]|1[0-2])$'}},required:['month'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const m=(input as {month?:unknown})?.month;if(typeof m!=='string'||!/^20\d{2}-(0[1-9]|1[0-2])$/.test(m))throw new Error('Mes no válido');const result=await act({action:'generate',month:m},'Borrador generado');setMonth(m);setTab('menu');return {month:m,days:result.state.menus[m].days.length,status:'draft'}}},{signal:lifecycle.signal})).catch(()=>{});
  return()=>lifecycle.abort();
 },[]);
 useEffect(()=>{if(edit)dialog.current?.showModal();else dialog.current?.close()},[edit?.id]);
 const menu=data.state.menus[month];const settings=menu?.settings??data.state.settings;
 const activeDays=[1,2,3,4,5,6,0].filter(d=>settings.days.includes(d));
 const dates=monthDates(month,settings.days);const byDate=new Map(menu?.days.map(d=>[d.date,d])??[]);
 const allDays=Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);
 const weeks: (string|null)[][]=[];let row:(string|null)[]=Array(activeDays.length).fill(null);
 for(const date of allDays){const dow=new Date(date+'T12:00:00Z').getUTCDay();if(dow===1&&row.some(Boolean)){weeks.push(row);row=Array(activeDays.length).fill(null)}const col=activeDays.indexOf(dow);if(col>=0)row[col]=date}if(row.some(Boolean))weeks.push(row);
 const filtered=data.catalog.filter(d=>normalize(d.name).includes(normalize(query))&&(!category||d.category===category)&&(!person||d.person===person)&&(!onlyReview||d.review));
 const saved=Object.values(data.state.menus).sort((a,b)=>b.month.localeCompare(a.month));
 const next=nextMonth(month);const available=!loading&&!busy&&!auth;
 const shared=menu?.days.filter(d=>!d.suggestion&&(d.manual?d.manual.kind==='custom'&&d.manual.Dani===d.manual.Marta:d.meals.Dani.map(x=>x.id).join()===d.meals.Marta.map(x=>x.id).join())).length??0;
 const plannedCount=menu?menu.days.filter(d=>!d.manual||d.manual.kind==='custom').length:dates.length;
 function openEdit(d:Dish){setError('');setEdit({...d})}
 function newDish(){setError('');setEdit({id:0,name:'',category:'Verduras',season:'Ambos',complexity:2,person:'Ambos',type:'Único',review:false,enabled:true})}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`a-la-mesa-${currentMonth()}.json`;a.click();URL.revokeObjectURL(url)}
 function mealDay(day:Day){
 if(day.suggestion){const recipe=recipes.find(r=>r.id===day.suggestion);return <div className="suggestion"><span className="category">Receta por probar</span><strong>{recipe?.name??'Propuesta retirada'}</strong><p>{recipe?'Pendiente de confirmar quién la come.':'Esta receta ya no está en las sugerencias. Sustitúyela por un plato habitual.'}</p><div className="suggestion-actions"><button disabled={!available||!recipe} onClick={()=>{if(recipe){setError('');setRecipeView({recipe,date:day.date})}}}>Ver y aceptar</button><button disabled={!available} onClick={()=>run({action:'reject-recipe',month,date:day.date},'Propuesta sustituida por una comida de vuestro catálogo.')}>Usar plato habitual</button></div></div>}

 if(day.manual){const m=day.manual;if(m.kind==='custom')return <div className="manual-meal"><span className="category">Comida puntual</span>{m.Dani===m.Marta?<><span className="person">Para los dos</span><p>{m.Dani}</p></>:people.map(p=><div key={p}><span className={p==='Dani'?'person dani':'person marta'}>{p}</span><p>{m[p]}</p></div>)}</div>;return <div className="manual-meal away"><span className="manual-symbol">{m.kind==='out'?<Utensils size={22}/>:<CalendarDays size={22}/>}</span><strong>{m.kind==='out'?'Comemos fuera':'Sin planificar'}</strong>{m.note&&<p>{m.note}</p>}</div>}
 const same=day.meals.Dani.map(x=>x.id).join()===day.meals.Marta.map(x=>x.id).join();const groups=same?[{label:'Para los dos',dishes:day.meals.Dani}]:people.map(p=>({label:p,dishes:day.meals[p]}));return groups.map(g=><div className="meal-group" key={g.label}><span className={g.label==='Dani'?'person dani':g.label==='Marta'?'person marta':'person'}>{g.label}</span>{g.dishes.map(d=><div key={d.id} className="meal"><span className={tag(d.category)}>{d.category}</span><button className="dish-name" onClick={()=>{setError('');setDishRecipe(data.catalog.find(x=>x.id===d.id)??d)}}>{d.name}</button><small>{d.type}{d.review?' · Revisar':''}</small></div>)}</div>)}
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Utensils size={24}/></span><span>A la mesa<small>DANI & MARTA</small></span></a><nav>{[{id:'menu',label:'Menú mensual',Icon:CalendarDays},{id:'history',label:'Meses guardados',Icon:History},{id:'catalog',label:'Nuestros platos',Icon:BookOpen},{id:'recipes',label:'Descubrir recetas',Icon:Sparkles},{id:'shopping',label:'Lista de la compra',Icon:ShoppingBasket},{id:'settings',label:'Preferencias',Icon:Settings2}].map(({id,label,Icon})=><button className={tab===id?'active':''} aria-current={tab===id?'page':undefined} key={id} onClick={()=>{setTab(id);setNotice('')}}><Icon size={20}/>{label}</button>)}</nav><div className="sidebar-bottom"><img src="/mesa.jpg" width="192" height="100" alt="Ensalada casera de verduras y garbanzos"/><div className="avatars"><b>D</b><b>M</b></div><strong>Una mesa para dos</strong><p>{data.catalog.length} platos de vuestra cocina</p></div></aside>
 <main><header className="topline"><span>EL MENÚ DE CASA</span><span>Dani y Marta · Solo comidas</span></header>
 <section className="heading"><div><p className="eyebrow">{tab==='shopping'?'ANTES DE IR A COMPRAR':tab==='recipes'?'ALGO NUEVO EN LA MESA':tab==='menu'?'PLANIFICAMOS EL MES':tab==='catalog'?'VUESTRA COCINA':tab==='history'?'LO QUE HEMOS PREPARADO':'A VUESTRO GUSTO'}</p><h1>{tab==='shopping'?'Lista de la compra':tab==='recipes'?'Descubrir recetas':tab==='menu'?'¿Qué comemos?':tab==='catalog'?'Nuestros platos':tab==='history'?'Meses guardados':'Preferencias'}</h1><p>{tab==='shopping'?'Toda vuestra compra: ingredientes del menú y productos que añadáis.':tab==='recipes'?'Nuevas ideas, ingredientes conocidos y recetas en español.':tab==='menu'?'Vuestros platos de siempre, con un poco más de orden.':tab==='catalog'?'El catálogo del Excel, listo para revisar y ajustar.':tab==='history'?'Los meses confirmados ayudan a variar los siguientes.':'Decidid qué días cocinar y cómo repartir las recetas.'}</p></div>{tab==='menu'&&<button className="primary" disabled={!available} onClick={()=>{setMonth(next);if(!data.state.menus[next])run({action:'generate',month:next},'El próximo mes ya tiene borrador.')}}><Sparkles size={18}/>Generar próximo mes</button>}{tab==='catalog'&&<div className="catalog-actions"><button disabled={!available} onClick={()=>exportCatalog(data.catalog)}><Download size={17}/>Exportar JSON</button><button disabled={!available} onClick={()=>setImportOpen(true)}><Upload size={17}/>Importar JSON</button><button className="primary" disabled={!available} onClick={newDish}><Plus size={18}/>Nuevo plato</button></div>}{tab==='history'&&<button disabled={!available} onClick={exportData}><Download size={18}/>Exportar copia</button>}</section>
 {loading&&<div className="message"><LoaderCircle className="spin" size={18}/>Cargando vuestros menús…</div>}
 {error&&<div className="message error" role="alert"><AlertCircle size={18}/><span>{error}</span>{auth?<a href="/signin-with-chatgpt?return_to=/" target="_top">Iniciar sesión</a>:<button onClick={()=>void load()}>Recargar</button>}</div>}
 {notice&&<div className="message success" role="status"><Check size={18}/>{notice}</div>}
 {tab==='menu'&&<>
 <section className="monthbar"><div><button aria-label="Mes anterior" onClick={()=>setMonth(nextMonth(month,-1))}><ChevronLeft size={20}/></button><h2>{title(month)}</h2><button aria-label="Mes siguiente" onClick={()=>setMonth(next)}><ChevronRight size={20}/></button></div><span className="pill">{plannedCount} comidas · {menu?.status==='confirmed'?'Confirmado':menu?'Borrador':'Por preparar'}</span></section>
 {!menu?<div className="empty"><CalendarDays size={40}/><h2>Un mes por preparar</h2><p>Genera las comidas de {months[Number(month.slice(5))-1].toLowerCase()}. Tendremos en cuenta quién come cada plato, la temporada y los meses confirmados.</p><button className="primary" disabled={!available} onClick={()=>run({action:'generate',month},'Borrador generado. Puedes cambiar días antes de confirmarlo.')}><Sparkles size={18}/>Generar este mes</button><small>El histórico comienza con vuestro primer menú confirmado.</small></div>:<>
 <div className="menu-tools"><div><strong>{shared}</strong> días con el mismo menú para los dos <span className="divider">·</span> {menu.days.filter(d=>d.locked).length} días bloqueados</div><div>{menu.status==='draft'?<><button disabled={!available} onClick={()=>run({action:'generate',month},'Borrador regenerado. Se han conservado los días bloqueados.')}><RefreshCw size={16}/>Regenerar</button><button className="primary" disabled={!available} onClick={()=>run({action:'confirm',month},'Menú confirmado. Se tendrá en cuenta para la rotación.')}><Check size={17}/>Confirmar menú</button></>:<button disabled={!available} onClick={()=>run({action:'edit',month},'Menú abierto como borrador. Confírmalo al terminar.')}><Pencil size={16}/>Editar menú</button>}</div></div>
 {menu.warnings.length>0&&<details className="warnings"><summary><AlertCircle size={16}/> {menu.warnings.length} notas para revisar</summary>{menu.warnings.map(w=><p key={w}>{w}</p>)}</details>}
 <div className="calendar" style={{'--columns':activeDays.length} as React.CSSProperties}><div className="weekday-row">{activeDays.map(d=><div key={d}>{dayNames[d]}</div>)}</div>{weeks.map((week,i)=><div className="calendar-week" key={i}>{week.map((date,j)=>{const day=date?byDate.get(date):undefined;return <article className={`day ${date?'':'outside'} ${day?.locked?'locked':''}`} key={date??`blank-${j}`}>{date&&<><div className="day-top"><span><b>{Number(date.slice(8))}</b><em>{dayNames[new Date(date+'T12:00:00Z').getUTCDay()]}</em></span>{day&&menu.status==='draft'&&<div><button className="edit-day-button" title="Editar comida del día" aria-label={`Editar comida del ${date}`} disabled={!available} onClick={()=>{setError('');setEditDay(day)}}><Pencil size={15}/></button><button title={day.locked?'Desbloquear día':'Conservar este día al regenerar'} aria-label={`${day.locked?'Desbloquear':'Bloquear'} ${date}`} disabled={!available} onClick={()=>run({action:'lock',month,date},day.locked?'Día desbloqueado.':'Día bloqueado. Se conservará al regenerar.')}>{day.locked?<LockKeyhole size={15}/>:<Unlock size={15}/>}</button><button title={day.locked&&!day.suggestion?'Desbloquea el día para proponer una receta nueva':'Proponer una receta nueva'} aria-label={`Proponer una receta nueva para el ${date}`} disabled={!available||(day.locked&&!day.suggestion)} onClick={()=>run({action:'suggest-recipe',month,date},'Nueva receta propuesta. Puedes aceptarla o sustituirla por un plato habitual.')}><Sparkles size={15}/></button><button title="Cambiar comidas de este día" aria-label={`Cambiar comidas del ${date}`} disabled={!available||day.locked} onClick={()=>run({action:'reroll',month,date},'Comidas del día cambiadas.')}><RefreshCw size={15}/></button></div>}</div>{day?mealDay(day):<p>Sin comida asignada</p>}</>}</article>})}</div>)}</div><p className="footnote">La composición de las comidas sigue los tipos de vuestro catálogo. Solo los meses confirmados cuentan para la rotación. Se proponen hasta dos recetas nuevas automáticamente. Usad el icono de destellos de cada día para pedir más, según temporada y disponibilidad. Aceptadlas o sustituidlas antes de confirmar.</p></>}
 </>}
 {tab==='shopping'&&<Shopping store={data.state.shopping} busy={!available} onAction={a=>act(a,'Lista de la compra guardada.')} initialMonth={month} menus={data.state.menus} catalog={data.catalog} onEdit={dish=>{setError('');setDishRecipe(dish)}}/>}
 {tab==='recipes'&&<DiscoverRecipes catalog={data.catalog} onOpen={recipe=>{setError('');setRecipeView({recipe})}}/>}
 {tab==='history'&&<div className="history-grid">{saved.length?saved.map(m=><button className="history-card" key={m.month} onClick={()=>{setMonth(m.month);setTab('menu')}}><CalendarDays size={25}/><h2>{title(m.month)}</h2><span>{m.days.filter(d=>!d.manual||d.manual.kind==='custom').length} comidas</span><span className="pill">{m.status==='confirmed'?'Confirmado':'Borrador'}</span><ChevronRight size={20}/></button>):<div className="empty"><History size={38}/><h2>Todavía no hay meses guardados</h2><p>Genera tu primer menú. Los borradores también se guardan para continuar más tarde.</p><button onClick={()=>setTab('menu')}>Ir al menú mensual</button></div>}</div>}
 {tab==='catalog'&&<><div className="filters"><label className="search"><Search size={18}/><input aria-label="Buscar plato" placeholder="Buscar un plato…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(40)}}/></label><select aria-label="Filtrar por grupo" value={category} onChange={e=>{setCategory(e.target.value);setLimit(40)}}><option value="">Todos los grupos</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filtrar por persona" value={person} onChange={e=>{setPerson(e.target.value);setLimit(40)}}><option value="">Todas las personas</option>{['Ambos','Dani','Marta'].map(p=><option key={p}>{p}</option>)}</select><label className="check"><input type="checkbox" checked={onlyReview} onChange={e=>{setOnlyReview(e.target.checked);setLimit(40)}}/>Por revisar</label></div><div className="catalog-summary">{filtered.length} platos <span>Haz clic en un plato para revisar sus datos.</span></div><div className="table-wrap"><table><thead><tr><th>Plato</th><th>Grupo</th><th>Persona</th><th>Tipo</th><th>Temporada</th><th>Complejidad</th></tr></thead><tbody>{filtered.slice(0,limit).map(d=><tr key={d.id} className={d.enabled===false?'disabled-row':''}><td><button className="table-dish" onClick={()=>openEdit(d)}>{d.name}<Pencil size={13}/></button><button className="recipe-link" onClick={()=>{setError('');setDishRecipe(d)}}>Ver / editar receta</button>{d.review&&<small className="review">Por revisar</small>}{d.enabled===false&&<small> · Excluido</small>}</td><td><span className={tag(d.category)}>{d.category}</span></td><td>{d.person==='Ambos'?'Los dos':d.person}</td><td>{d.type}</td><td>{d.season==='Ambos'?'Todo el año':d.season}</td><td>{d.complexity} / 5</td></tr>)}</tbody></table>{filtered.length===0&&<p className="no-results">No hay platos con estos filtros.</p>}</div>{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+60)}>Mostrar más platos</button>}</>}
 {tab==='settings'&&<form className="settings" onSubmit={e=>{e.preventDefault();run({action:'settings',settings:prefs},'Preferencias guardadas. Se aplicarán al generar o regenerar un mes.')}}><section><h2>Días que planificamos</h2><p>Podéis incluir el fin de semana cuando queráis.</p><div className="choice-row">{[1,2,3,4,5,6,0].map(d=><label className={prefs.days.includes(d)?'chosen':''} key={d}><input type="checkbox" checked={prefs.days.includes(d)} onChange={()=>setPrefs({...prefs,days:prefs.days.includes(d)?prefs.days.filter(x=>x!==d):[...prefs.days,d]})}/>{dayNames[d]}</label>)}</div></section><section><h2>Temporada de verano</h2><p>Por defecto, de junio a septiembre. El resto de meses utiliza los platos de invierno. «Todo el año» se permite siempre.</p><div className="choice-row">{months.map((m,i)=><label className={prefs.summerMonths.includes(i+1)?'chosen':''} key={m}><input type="checkbox" checked={prefs.summerMonths.includes(i+1)} onChange={()=>setPrefs({...prefs,summerMonths:prefs.summerMonths.includes(i+1)?prefs.summerMonths.filter(x=>x!==i+1):[...prefs.summerMonths,i+1]})}/>{m}</label>)}</div></section><section className="settings-pair"><div><h2>Complejidad y frecuencia</h2><p>Los platos sencillos salen más a menudo. Los de complejidad alta también participan, pero se espacian más. No hace falta pasar por todo el catálogo antes de repetir.</p></div><label>Separación orientativa · complejidad 3<select value={prefs.repeatDays} onChange={e=>setPrefs({...prefs,repeatDays:Number(e.target.value)})}>{[7,14,21,30,45,60,90].map(v=><option key={v} value={v}>{v} días</option>)}</select></label></section><p className="footnote">Las personas y la temporada se respetan siempre. La separación se acorta para platos sencillos y se alarga para los más complejos; es una preferencia, no un límite. Los menús existentes conservan sus ajustes hasta que los regeneres.</p><button className="primary" disabled={!available||!prefs.days.length}><Check size={18}/>Guardar preferencias</button></form>}
 <footer>A la mesa · Hecho para vuestra cocina <a href="https://unsplash.com/photos/bowl-of-vegetable-salads-IGfIGP5ONV0" target="_blank" rel="noreferrer">Foto: Anna Pelzer</a></footer>
 </main><dialog ref={dialog} onCancel={()=>setEdit(null)} onClick={e=>{if(e.target===dialog.current)setEdit(null)}}>{edit&&<form onSubmit={async e=>{e.preventDefault();try{const {id,...newValues}=edit;await act({action:id?'dish':'create-dish',dish:id?edit:newValues},id?'Plato guardado. Los menús ya guardados mantienen su versión; los nuevos usarán estos datos.':'Nuevo plato añadido al catálogo. Ya está disponible para generar menús.');if(!id){setQuery(edit.name);setCategory('');setPerson('');setOnlyReview(false);setTab('catalog')}setEdit(null);}catch{}}}><div className="dialog-header"><h2>{edit.id?'Revisar plato':'Nuevo plato'}</h2><button type="button" aria-label="Cerrar" onClick={()=>setEdit(null)}><X size={20}/></button></div>{edit.id>0&&<button type="button" className="recipe-link" onClick={()=>{setEdit(null);setDishRecipe(data.catalog.find(d=>d.id===edit.id)??edit)}}>Ver / editar ingredientes y preparación</button>}<label>Nombre<input value={edit.name} required maxLength={180} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className="form-grid">{[{key:'category',label:'Grupo',values:categories},{key:'person',label:'Lo come',values:['Ambos','Dani','Marta']},{key:'type',label:'Tipo de plato',values:['Único','Entrante','Principal','Guarnición']},{key:'season',label:'Temporada',values:['Ambos','Verano','Invierno']}].map(f=><label key={f.key}>{f.label}<select value={String(edit[f.key as keyof Dish])} onChange={e=>setEdit({...edit,[f.key]:e.target.value})}>{f.values.map(v=><option key={v} value={v}>{v==='Ambos'?(f.key==='person'?'Los dos':'Todo el año'):v}</option>)}</select></label>)}<label>Complejidad<select value={edit.complexity} onChange={e=>setEdit({...edit,complexity:Number(e.target.value)})}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{v} / 5</option>)}</select></label><label>Familia de recetas<input placeholder="Automática" maxLength={80} value={edit.family??''} onChange={e=>setEdit({...edit,family:e.target.value})}/></label></div><p className="footnote">La familia ayuda a espaciar recetas parecidas. Una guarnición no se utilizará como comida completa.</p><label className="check"><input type="checkbox" checked={edit.review} onChange={e=>setEdit({...edit,review:e.target.checked})}/>Pendiente de revisar</label><label className="check"><input type="checkbox" checked={edit.enabled!==false} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/>Disponible para generar menús</label>{error&&<p className="dialog-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={()=>setEdit(null)}>Cancelar</button><button className="primary" disabled={!available}><Check size={17}/>{edit.id?'Guardar plato':'Añadir plato'}</button></div></form>}</dialog>
 {dishRecipe&&<DishRecipe key={dishRecipe.id} dish={dishRecipe} busy={!available} error={error} onClose={()=>setDishRecipe(null)} onSave={async recipe=>{await act({action:'recipe',id:dishRecipe.id,recipe},'Receta guardada. La lista de la compra usará estos datos.');setDishRecipe(null)}}/>}
 {importOpen&&<ImportCatalog revision={data.revision} busy={!available} onClose={()=>setImportOpen(false)} onApply={async document=>{await act({action:'import-catalog',document},'Catálogo importado. Los menús guardados se conservan.')}}/>}
 {recipeView&&<RecipeDialog key={recipeView.recipe.id} recipe={recipeView.recipe} inMenu={!!recipeView.date} catalog={data.catalog} busy={!available} error={error} onClose={()=>setRecipeView(null)} onAccept={async dish=>{await act({action:'accept-recipe',recipeId:recipeView.recipe.id,dish,...(recipeView.date?{month,date:recipeView.date}:{})},recipeView.date?'Receta añadida y comida del día completada y bloqueada.':'Receta añadida a vuestros platos.');setRecipeView(null)}}/>}
 {editDay&&<DayEditor day={editDay} busy={busy} error={error} onClose={()=>setEditDay(null)} onSave={async manual=>{await act({action:'day-manual',month,date:editDay.date,manual},'Día guardado y bloqueado. Se conservará al regenerar.');setEditDay(null)}}/>}
 </div>
}
