'use client';
import {useEffect,useMemo,useState} from 'react';
import {Download,ShoppingBasket} from 'lucide-react';
import {shoppingList} from '../lib/shopping';
import type {Dish,Menu} from '../lib/menu';
import {downloadText} from './catalog-transfer';
const number=(n:number)=>new Intl.NumberFormat('es',{maximumFractionDigits:3}).format(n);
export default function Shopping({initialMonth,menus,catalog,onEdit}:{initialMonth:string;menus:Record<string,Menu>;catalog:Dish[];onEdit:(dish:Dish)=>void}){
 const confirmed=Object.values(menus).filter(m=>m.status==='confirmed').sort((a,b)=>b.month.localeCompare(a.month));const [month,setMonth]=useState(menus[initialMonth]?.status==='confirmed'?initialMonth:confirmed[0]?.month??'');const menu=menus[month]?.status==='confirmed'?menus[month]:confirmed[0];
 const [from,setFrom]=useState(menu?.month+'-01'),[to,setTo]=useState(menu?.month+'-31');const [checked,setChecked]=useState<Set<string>>(new Set());
 useEffect(()=>{if(menu){setFrom(menu.month+'-01');const [y,m]=menu.month.split('-').map(Number);setTo(menu.month+'-'+new Date(Date.UTC(y,m,0)).getUTCDate());setChecked(new Set())}},[menu?.month]);
 const endOfMonth=menu?new Date(Date.UTC(Number(menu.month.slice(0,4)),Number(menu.month.slice(5)),0)).toISOString().slice(0,10):'';
 const list=useMemo(()=>menu?shoppingList(menu,catalog,from,to):null,[menu,catalog,from,to]);useEffect(()=>setChecked(new Set()),[month,from,to,catalog]);
 if(!menu||!list)return <div className="empty"><ShoppingBasket size={38}/><h2>Confirma un menú para preparar la compra</h2><p>La lista se calculará con las recetas actuales de los platos del menú.</p></div>;
 function exportList(){downloadText(`compra-${from}-${to}.txt`,[`LISTA DE LA COMPRA · ${from} a ${to}`,`Cobertura: ${list!.readyPortions} de ${list!.portions} raciones de platos con cantidades completas.`,...list!.items.map(i=>`${checked.has(i.key)?'[x]':'[ ]'} ${i.name}: ${number(i.quantity)} ${i.unit}`),'','PENDIENTES DE REVISAR',...list!.pending.map(p=>`${p.name}: ${p.reason} (${p.dates.join(', ')})`)].join('\n'),'text/plain;charset=utf-8')}
 return <><div className="filters shopping-filters"><label>Menú confirmado<select value={menu.month} onChange={e=>setMonth(e.target.value)}>{confirmed.map(m=><option key={m.month}>{m.month}</option>)}</select></label><label>Desde<input type="date" min={menu.month+'-01'} max={endOfMonth} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" min={from} max={menu.month+'-31'} value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={exportList} disabled={!from||!to||from>to}><Download size={17}/>Exportar lista</button></div>{from>to?<p className="message error">La fecha final debe ser posterior a la inicial.</p>:<><div className="recipe-intro"><ShoppingBasket size={25}/><div><strong>{list.pending.length?'Lista parcial · hay datos por completar':'Lista calculada'}</strong><p>{list.readyPortions} de {list.portions} raciones de platos tienen cantidades completas. Se cuentan dos personas cuando comparten plato y una para cada plato individual.</p></div></div><p className="footnote">Las cantidades se suman por ingrediente y unidad. Solo se convierten kg a g y litros a ml; no se equiparan tazas y gramos. Puedes marcar lo que ya tienes. Las marcas se reinician al cambiar el periodo o las recetas.</p>{!list.items.length?<div className="empty compact"><h3>Aún no hay cantidades para sumar</h3><p>Completa las fichas pendientes de abajo y marca sus ingredientes y raciones como revisados.</p></div>:<div className="shopping-list">{list.items.map(i=><div className="shopping-item" key={i.key}><label><input type="checkbox" checked={checked.has(i.key)} onChange={()=>setChecked(old=>{const next=new Set(old);if(next.has(i.key))next.delete(i.key);else next.add(i.key);return next})}/><span className={checked.has(i.key)?'bought':''}>{i.name}</span><strong>{number(i.quantity)} {i.unit}</strong></label><details><summary>Ver platos y días</summary>{i.uses.map((u,n)=><p key={n}>{u}</p>)}</details></div>)}</div>}{list.pending.length>0&&<section className="shopping-pending"><h2>Falta revisar</h2><p>Estos elementos no están incluidos en las cantidades de arriba.</p>{list.pending.map((p,n)=><div key={n}><span><strong>{p.name}</strong><small>{p.reason} {p.dates.join(', ')}</small></span>{p.dishId&&catalog.some(d=>d.id===p.dishId)&&<button onClick={()=>onEdit(catalog.find(d=>d.id===p.dishId)!)}>Editar receta</button>}</div>)}</section>}</>}</>;
}
